[default]
SQLALCHEMY_DATABASE_URI = 'sqlite:///development.db'
DEBUG = false
TITLE = "Nueva Acropolis"
EXTENSIONS = [
    "nacropolis.ext.database:init_app",
    "nacropolis.ext.commands:init_app",
]


[development]
EXTENSIONS = [
    "dynaconf_merge_unique"
]


